//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mark()
        {
            this.marks_comments = new HashSet<marks_comments>();
            this.marks_history = new HashSet<marks_history>();
        }
    
        public int Id { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Month { get; set; }
        public string Value { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public Nullable<int> TeacherId { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual typeMark typeMark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marks_comments> marks_comments { get; set; }
        public virtual student student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marks_history> marks_history { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
