//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Month { get; set; }
        public string Value { get; set; }
    
        public virtual student studetn { get; set; }
        public virtual subject subject { get; set; }
        public virtual typeMark typeMark { get; set; }
    }
}
