//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects_to_groups
    {
        public int Id { get; set; }
        public string GroupId { get; set; }
        public int SubjectId { get; set; }
    
        public virtual group group { get; set; }
        public virtual subject subject { get; set; }
    }
}
