//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentAvgMarkWithGroup
    {
        public string PassportId { get; set; }
        public string Fio { get; set; }
        public string GroupId { get; set; }
        public Nullable<int> SubjectCount { get; set; }
        public Nullable<double> AvgMark { get; set; }
    }
}
